<h3>Sistema te Autenticacion por Certificados para Android</h3>
<?
if (array_key_exists('SSL_CLIENT_S_DN_CN',$_SERVER)){
  $user = $_SERVER['SSL_CLIENT_S_DN_CN'];
  echo "Estas autenticado como <b>$user</b><br>";
}
?>

<a href="https://home.bacamt.com:83/generate/">Crear nueva clave</a><br>
<a href="https://home.bacamt.com:83/secure/list.phtml">Lista de certificados en uso</a><br>
<a href="https://home.bacamt.com:83/secure/revoke.phtml">Revocar certificado de usuario</a><br>
<a href="https://home.bacamt.com:83/access.log">Log de acceso</a><br>
<a href="https://home.bacamt.com:83/error.log">Log de errores</a><br>
<a href="https://home.bacamt.com:83/ca.crt">Descargar certificado CA</a>

<pre>
<? print_r($_SERVER); ?>
</pre>

